### ISSUE TITLE
[REQUEST] How to use strapi for your mobile app

### ISSUE THREAD

**Issue by Mcastres** [strapi/strapi-tutorials#11]
**My Request**
There is actually 0 tutorials on how to use strapi for your mobile application and it has to change! The reason why headless CMS exists is the fact that today new devices are part of our life next to  computers like smartphones!
We must therefore offer a tutorial on using strapi for creating mobile app so if you are interested and wish to create the first tutorial of this kind take off the rocket below!

**Preferred Format**
- [x] Article
- [x] Video

**Community vote**
👍 Upvote if you need it too
🚀 If you can make the tutorial to help the community!

**Comment by fabio-nettis** [comment]
Does it have to be a native application (codebade Kotlin, Swift, Objective-C)? I could provide react-native examples with GraphQL.

**Comment by Mcastres** [comment]
Absolutely not! Actually, React Native is the best way to go  :)

**Comment by fabio-nettis** [comment]
Well since I'm currently working on "Gravity" a strapi client based on react-native and apollo if you want to wait, it's absolutly open source and planned for Q1 2020.
