### ISSUE TITLE
[REQUEST] How do i change the file limit when i import CSV file for mongoDB

### ISSUE THREAD

**Issue by Zubair-Ashraf** [strapi/strapi-tutorials#19]
I want to import CSV file in mongoDB using strapi, for that i used this plugin that's really good plugin.
but the one issue i faced during import CSV file, that is file data limit.
My file data limit is (2000+ rows) that i want to import but its throw error(Payload Too Large) when i import this big file.

so, please help me to resolve this issue or tell me how do i change/increase the file limit.
Thanks

**Comment by pouyamiralayi** [comment]
Hi @Zubair-Ashraf  
This is going to be fixed on the upcoming tutorial, but for now you can do it this way:

checkout ``node_modules/raw-body/index.js`` which has a function named ``getRawBody`` with a line of code like below:
```
  // convert the limit to an integer
  var limit = bytes.parse(opts.limit)
```
you can assign a value to the ``limit`` variable with the following format:
```
number of bytes or any string like '1000', '500kb' or '3mb'.
```
Cheers!

**Comment by Zubair-Ashraf** [comment]
> Hi @Zubair-Ashraf
> This is going to be fixed on the upcoming tutorial, but for now you can do it this way:
> 
> checkout `node_modules/raw-body/index.js` which has a function named `getRawBody` with a line of code like below:
> 
> ```
>   // convert the limit to an integer
>   var limit = bytes.parse(opts.limit)
> ```
> 
> you can assign a value to the `limit` variable with the following format:
> 
> ```
> number of bytes or any string like '1000', '500kb' or '3mb'.
> ```
> 
> Cheers!

According to your guideline i changed the node_modules/raw-body/index.js it works fine.
Thanks you so much for the response and help 😊
