### ISSUE TITLE
Creating a photo gallery app with Strapi and 11ty

### ISSUE THREAD

**Issue by Quadrisheriff** [strapi/strapi-tutorials#520]
**My resource**

Hi, I will like a create a new tutorial about creating a photo gallery website with Strapi and 11ty. I recently used 11ty in a project, and I really liked the framework. This is the outline for the tutorial. 

Outline

- Introduction
- Prerequisites
- Backend Setup
    - Strapi Setup
    - Cloudinary installation and set up
    - Creating Photos collection type
    - Allowing Access to the backend
- Frontend Setup
    - 11ty and Tailwind CSS Setup
    - Connect Strapi backend to 11ty frontend
    - Creating 11ty file structure
    - Creating Website's layout
    - Importing and displaying data from Strapi
- Conclusion

Also, I am committed to updating the article after the Strapi V4 release.

**Comment by ShadaW11** [comment]
@Quadrisheriff I feel that the tutorial can include more features. Could you think about additional interesting features to be added in the tutorial?

**Comment by Quadrisheriff** [comment]
Hi @ShadaW11 , I have updated the outline. You can check again now.

**Comment by ShadaW11** [comment]
Hello @Quadrisheriff looks good, I would suggest that you start working on it after the release of the V4 (after 2/3 days) so the app is already V4 updated. okay?

**Comment by ShadaW11** [comment]
@Quadrisheriff please update the outline so I can approve it.

**Comment by ShadaW11** [comment]
@Quadrisheriff Do you commit to updating the screenshots at the end of the month once the final V4 is released without additional compensation. If yes, please confirm and go ahead and start working on it.

**Comment by Quadrisheriff** [comment]
Yes, I confirm

**Comment by ShadaW11** [comment]
Awesome, please feel free to go ahead.

**Comment by Quadrisheriff** [comment]
Hi @ShadaW11 , the tutorial is complete - https://www.dropbox.com/scl/fi/yq0erwtgx6m33924ovauy/Building-a-Photogallery-app-with-Strapi-Eleventy-Tailwind-CSS-and-Cloudinary.paper?dl=0&rlkey=0ozsaqey8iejy0c58yrq9trm7

**Comment by ShadaW11** [comment]
Thank you @Quadrisheriff will get back to you soon.
