### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Caching in Strapi with Strapi Middleware Cache

### ISSUE THREAD

**Issue by ShadaW11** [strapi/strapi-tutorials#833]
**Description**

This article requires update
https://strapi.io/blog/caching-in-strapi-strapi-middleware-cache

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Umoren** [comment]
🚀 I can help you

**Comment by dessireugarte** [comment]
@Umoren If this is your first article update, please review this guide quickly before you get started. https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d

You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).

Once your article is ready, please share the dropbox link to your article in a comment in your GitHub issue.

**Comment by Umoren** [comment]
Hi @dessireugarte 
I am suggesting a change of article title from "Caching in Strapi with Strapi Middleware Cache" to "Caching in Strapi with Strapi Plugin Rest Cache"
This is because:
- version 4 doesn't support adding cache settings in `middlewares.js`
- https://strapi-community.github.io/strapi-plugin-rest-cache is the version of https://github.com/patrixr/strapi-middleware-cache/ supported in strapi v4
- the content from the [original article](https://strapi.io/blog/caching-in-strapi-strapi-middleware-cache) will be different but the goal is the same; to show strapi users how to configure caching with redis server

**Comment by dessireugarte** [comment]
@Umoren good catch! 
It makes sense so please go ahead! 👍

**Comment by Umoren** [comment]
Hi @dessireugarte 
I'm done with the initial draft
https://www.dropbox.com/scl/fi/jmu0jz5gredxlyrsr4sbj/Caching-in-Strapi-with-Strapi-Plugin-Rest-Cache.paper?dl=0&rlkey=1umb3trp3737wn3m1uv7g88t3

**Comment by dessireugarte** [comment]
Thanks @Umoren!
I assigned @TiaraOluwanimi so your article is reviewed. If there is any change we might need, we will let you know!

**Comment by Umoren** [comment]
Hello @dessireugarte 
Any updates on when this will be published?

**Comment by dessireugarte** [comment]
Hello @Umoren  👋
I just wanted to let you know that your article will be published around the third week of September. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hello @Umoren  👋 
Your article is [live](https://strapi.io/blog/caching-in-strapi-with-rest-cache-plugin)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by Umoren** [comment]
Thanks @dessireugarte 
Please who do i contact if i'm having issues with sending invoice?

**Comment by dessireugarte** [comment]
Hello @Umoren 👋 You can contact @malgamves. 
What is the issue you are facing?

**Comment by malgamves** [comment]
hey @Umoren let's continue the conversation over email. I sent you something to clarify

**Comment by Umoren** [comment]
Alright
