### ISSUE TITLE
How To Build a Hotel Management App Using Strapi and NExt.js 1/7[SUBMIT]

### ISSUE THREAD

**Issue by olujerry** [strapi/strapi-tutorials#911]
**My resource**
<!--
Hello 👋 
Hotel management applications are popular because they allow users to explore the appearance of their hotel rooms as well as make reservations for themselves and their loved ones, enabling them to plan their budget.

This tutorial will show you how to utilize [Next.js](https://strapi.io/integrations/nextjs-cms) (React 16.8 w/ hooks) to power your UI, together with GraphQL, Stripe, Strapi, and React Context to create a full-stack application powered by the powerful Strapi (Headless CMS).
 **What we intend to build.**
A hotel management application, We plan to develop an application that will make consumers' hotel stays more enjoyable, from signup through reservation.

User login, registration, authentication, image upload, room reservation, and Stripe integration will all be included in the app.
  A  brief outline:

-  Introduction to Hotel Management Systems
- What is Strapi
- Prerequisites 
- Overview of Next.Js
- Build Strapi CMS Backend
- Setting Up Strapi
- Next.js installation
- Building the interface
- Adding Images for Hotel Management App
- Reservation and checkout.
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@olujerry are you looking to write this article or someone else to pick up the topic?

**Comment by olujerry** [comment]
I want to write the article.

**Comment by PaulBratslavsky** [comment]
@olujerry awesome. Can you provide an outline for the series to give me more context on what you are going to cover before you start on the article?  Thank you.

**Comment by olujerry** [comment]
1.  Setup (part 1) -

-     Strapi installation 

- Creating collection types

- Next.js installation

2. Hotels Availability (part 2)

- Designing the hotel available page

- Location (country, State, City)

3.  Rooms Selection (part 3)

- Select the type of room you want.

- Choose rooms that suit your budget.

4. Authentication (part 4)

5.  Reservations (part 5)

6. Payment and check-in (part 6)

7. Deploy  (part 7)

**Comment by olujerry** [comment]
Hello Paul, I want to know if I can continue with the article.

**Comment by olujerry** [comment]
I already started with the 1st series.

**Comment by PaulBratslavsky** [comment]
I know it has been a while, just wanted to check on your progress and if you are still working on this?

**Comment by olujerry** [comment]
Yes I'm working on it and I'm almost done with it.  Just summit it before
the end of the month.
Thanks for checking on me

**Comment by olujerry** [comment]
The project is ready. The links 
Part 1: https://www.dropbox.com/scl/fi/x39yx7w653x1phmcgy1me/How-To-Build-a-Hotel-Management-App-Using-Strapi-and-NExt.js-15.paper?dl=0&rlkey=ecuqk1c5eoembompv75rygvmi
Part 2:https://www.dropbox.com/scl/fi/25gqpj4lwx8m8wfpqf5wq/How-To-Build-a-Hotel-Management-App-Using-Strapi-and-NExt.js-25.paper?dl=0&rlkey=ey3hc71wijibgjqg2mbw10us7
Part3:https://www.dropbox.com/scl/fi/d3ql2w730p0gi4i5f523t/How-To-Build-a-Hotel-Management-App-Using-Strapi-and-NExt.js-35.paper?dl=0&rlkey=yp4tsogedvte90kg3taq8msx5
Part 4:https://www.dropbox.com/scl/fi/ek5h99a846aro6wepgfp4/How-To-Build-a-Hotel-Management-App-Using-Strapi-and-Next.js-45.paper?dl=0&rlkey=g41n5gf6iquqw4pyg75xk9hyp
PART5:https://www.dropbox.com/scl/fi/epyw22n8zibjiph8o5haa/How-To-Build-a-Hotel-Management-App-Using-Strapi-and-NExt.js-55.paper?dl=0&rlkey=xeb0khar0bsfqefsskfiqivfj

**Comment by olujerry** [comment]
Hello Paul, I'm done with the articles. please check

**Comment by dessireugarte** [comment]
Hello @olujerry 👋
In order to review this article, we need you to merge everything in one single dropbox file please.

**Comment by olujerry** [comment]
https://www.dropbox.com/scl/fi/tk13cfs5cy7dmx0jeu4e3/How-To-Build-a-Hotel-Management-App-Using-Strapi-and-NExt.js-15.paper?dl=0&rlkey=pcubkk3g7pul9zos8ijaf1372

**Comment by olujerry** [comment]
Hello @PaulBratslavsky @dessireugarte any update on this article please.

**Comment by dessireugarte** [comment]
Hello @olujerry ! Could you please delete the cover images and consolidate them as one single article? This article is a single article, so to make it easier for authors to read, it needs to be written down like all the tutorials. Here is an example of how a tutorial would look like: 
https://strapi.io/blog/how-to-deploy-strapi-on-cloudflare-pages

**Comment by olujerry** [comment]
@dessireugarte @PaulBratslavsky Requested changes have been made. Please confirm it matches your expectation.

**Comment by olujerry** [comment]
@dessireugarte @PaulBratslavsky Please any update on the article.

**Comment by dessireugarte** [comment]
Hello @olujerry! Thanks for the draft! 
We will review the draft and get back to you with feedback.

**Comment by olujerry** [comment]
Hello @PaulBratslavsky @dessireugarte please any updates on the article

**Comment by dessireugarte** [comment]
Hello @olujerry!
We will publish it in the second week of April. We will let you know when it is live.

**Comment by dessireugarte** [comment]
Hello @olujerry!
I did a content review and made some grammatical changes, h2s and h3s. But there are a few things that are not clear to me. Could you please take a look at the comments I left?

**Comment by olujerry** [comment]
Hello @dessireugarte 
I already made the necessary changes to the comments you made on the article.

**Comment by olujerry** [comment]
Hello @dessireugarte any update.

**Comment by PaulBratslavsky** [comment]
@olujerry Your post is reviewed we will let you know when it is published.
